name: Github Actiosn 실행시켜보기

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello, World!"